# Generated by Django 5.1.3 on 2024-11-15 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Washer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Стиральная машина', max_length=255)),
                ('brand', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('height', models.CharField(blank=True, max_length=10, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('max_load', models.FloatField(blank=True, null=True)),
                ('load_type', models.CharField(choices=[('Фронтальная', 'Фронтальная'), ('Вертикальная', 'Вертикальная')], default='Фронтальная', max_length=12)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='WasherImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='washer_images/')),
                ('washer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='washers.washer')),
            ],
        ),
    ]
