# Generated by Django 5.1.3 on 2024-11-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridges', '0003_fridge_chamber_count_fridge_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridge',
            name='defrosting_type',
            field=models.CharField(choices=[('no_frost', 'No Frost'), ('manual', 'Ручная'), ('without_freezer', 'Без морозильника')], default='Ручная', max_length=20),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='freezer_location',
            field=models.CharField(choices=[('top', 'сверху'), ('bottom', 'снизу'), ('left', 'слева'), ('right', 'справа'), ('no', 'нет')], default='Верх', max_length=20),
        ),
    ]
