# Generated by Django 5.1.3 on 2024-11-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridges', '0005_alter_fridge_defrosting_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridge',
            name='defrosting_type',
            field=models.CharField(choices=[('No Frost', 'No Frost'), ('Ручная', 'Ручная'), ('Без морозильника', 'Без морозильника')], default='Ручная', max_length=20),
        ),
    ]
