# Generated by Django 5.1.3 on 2024-11-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridges', '0006_alter_fridge_defrosting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridge',
            name='brand',
            field=models.CharField(default='one', max_length=50),
            preserve_default=False,
        ),
    ]
