# Generated by Django 5.1.3 on 2024-11-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridges', '0007_fridge_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridge',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='height',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
