# Generated by Django 5.1.3 on 2024-11-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridges', '0008_alter_fridge_color_alter_fridge_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridge',
            name='name',
            field=models.CharField(default='Холодильник с морозильником', max_length=255),
        ),
    ]
